#include "../assets/utils/digits/digit0.xpm"
#include "../assets/utils/digits/digit1.xpm"
#include "../assets/utils/digits/digit2.xpm"
#include "../assets/utils/digits/digit3.xpm"
#include "../assets/utils/digits/digit4.xpm"
#include "../assets/utils/digits/digit5.xpm"
#include "../assets/utils/digits/digit6.xpm"
#include "../assets/utils/digits/digit7.xpm"
#include "../assets/utils/digits/digit8.xpm"
#include "../assets/utils/digits/digit9.xpm"
#include "../assets/utils/time/time-divider.xpm"

#include "../assets/utils/words/pacman_text.xpm"
#include "../assets/utils/words/play_text.xpm"
#include "../assets/utils/words/rules_text.xpm"
#include "../assets/utils/words/exit_text.xpm"
#include "../assets/utils/words/win_text.xpm"
#include "../assets/utils/words/score_text.xpm"
#include "../assets/utils/words/game_over_text.xpm"

#include "../assets/utils/cursor/cursor.xpm"

#include "../assets/ui-elements/maze.xpm"
#include "../assets/ui-elements/pacman.xpm"
#include "../assets/ui-elements/ghost_red.xpm"
#include "../assets/ui-elements/ghost_orange.xpm"
#include "../assets/ui-elements/ghost_pink.xpm"
#include "../assets/ui-elements/ghost_blue.xpm"
#include "../assets/ui-elements/small_coin.xpm"
#include "../assets/ui-elements/big_coin.xpm"
